# Generated by Django 4.2.2 on 2023-06-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
