# Generated by Django 4.2.2 on 2023-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
