# Generated by Django 4.2.2 on 2023-06-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='image',
        ),
    ]
