# Generated by Django 4.2.2 on 2023-06-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactMessage',
        ),
    ]
